### PR TITLE
Basic test script

### LINKED ISSUE #1: Basic Training Script

### LINKED ISSUE #2: Basic Testing Script

### PR DESCRIPTION
**Pull request by DimitrisKatsiros**
Closes #1 and #2  as this pull request solves both. @tyiannak please check out `-s` option,  as the `-s` applies the argmax function to the last layer. Is that ok ?

### CODE REVIEW

**Comment by tyiannak** [comment]
Please add the following arg param:
-L: level to go before softmax
(if L=0 just do classification, otherwise return array of features)

**Comment by tyiannak** [comment]
Other than my comment above, it works as expected.

**Comment by tyiannak** [comment]
@DimitrisKatsiros i've tested the scripts/basic_test.py with a model i had already trained using the other PR (basic_training) and it seems to work as expected. 
Just please add the -L argument

**Comment by tyiannak** [comment]
@DimitrisKatsiros. 
Getting this error when testing: 

Traceback (most recent call last):
  File "scripts/basic_test.py", line 85, in <module>
    test_model(modelpath=model, ifile=ifile, layers_dropped=layers_dropped)
  File "scripts/basic_test.py", line 27, in test_model
    model = torch.load(modelpath)
  File "/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Users/tyiannak/.pyenv/versions/3.7.3/lib/python3.7/site-packages/torch/serialization.py", line 765, in _legacy_load
    raise RuntimeError("Invalid magic number; corrupt file?")
RuntimeError: Invalid magic number; corrupt file?

**Comment by DimitrisKatsiros** [comment]
Can you please show me the command you typed? Is the model's extension .pt or .pty ?

**Comment by tyiannak** [comment]
actually changing during saving the pickle protocol:
    torch.save(best_model, modelname, pickle_protocol=4)
results in a model loads successfully.

**Comment by tyiannak** [comment]
it was pty. when i did the change in save it was pt and it worked

**Comment by DimitrisKatsiros** [comment]
Maybe the model which you had saved, was from the last version, which saved .pkl files. After the update, load() and save() are handled by pytorch. Are you sure that this was not the problem? Can you please check it? I am asking because I did not face any kind of similar problems. If not I will add the parameter.

**Comment by tyiannak** [comment]
you're right sorry for that @DimitrisKatsiros it seems i was using .pkl files. so ignore my previous comment.

**Comment by tyiannak** [comment]
2 last comments before merging:
- it seems it would be better remove the argmax if layers_dropped == 0 (i.e. keep it as it was before)
- also return classnames in the testing function

**Comment by DimitrisKatsiros** [comment]
> 2 last comments before merging:
> 
> - it seems it would be better remove the argmax if layers_dropped == 0 (i.e. keep it as it was before)
> 
> - also return classnames in the testing function 

- What do you mean when you say like it was before ? 
- also instead of numbers you suggest to return class names ?

**Comment by tyiannak** [comment]
I mean without the arg max 

And no I mean to also return the class names as a second returned variable

**Comment by DimitrisKatsiros** [comment]
Okay

**Comment by DimitrisKatsiros** [comment]
@tyiannak Please check the latest commits. I think issues #1 & #2 are resolved and the branch `basic_test_script` is ready to merge with `master`. Also reject **PL** for branch `basic_training_script` as it is merged **already** with the current one. If any problem occures, inform me please.

**Pull request merged**
